[Border]
width = 6
offset = 3
color = 0xFFFFA500
enable_bitmap_caching = true

[Window]
validation_interval = 250

[[Window.excluded]]
class = "Windows.UI.Core.CoreWindow"

[[Window.excluded]]
class = "Shell_TrayWnd"

[[Window.excluded]]
class = "TopLevelWindowForOverflowXamlIsland"

[[Window.excluded]]
class = "XamlExplorerHostIslandWindow"

[[Window.excluded]]
class = "ForegroundStaging"

[[Window.excluded]]
class = "Progman"

[[Window.excluded]]
class = "WorkerW"

[[Window.excluded]]
class = "XamlWindow"
text = "Snipping Tool Overlay"